version: '3'

services:
  laravel:
    image: 'php:8.0-fpm'
    volumes:
      - .:/var/www/html
    ports:
      - '8000:8000'

  mysql:
    image: 'mysql:5.7'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    ports:
      - '3306:3306'

  nginx:
    image: 'nginx:alpine'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    depends_on:
      - laravel
